/**
 * FontAwesome5 solid names for FontAwesome5 (@expo/vector-icons category picker).
 * Unknown icons saved from older builds fall back via resolveCategoryIcon().
 */
export const CATEGORY_ICON_CHOICES = [
  "apple-alt",
  "baby",
  "baby-carriage",
  "bath",
  "bicycle",
  "bolt",
  "book",
  "bread-slice",
  "broom",
  "building",
  "bus",
  "camera",
  "car",
  "carrot",
  "cat",
  "chalkboard-teacher",
  "clipboard",
  "clipboard-check",
  "clipboard-list",
  "coffee",
  "coins",
  "comment-dollar",
  "couch",
  "credit-card",
  "cut",
  "dog",
  "dollar-sign",
  "drumstick-bite",
  "dumbbell",
  "egg",
  "file-invoice",
  "file-invoice-dollar",
  "film",
  "gamepad",
  "gas-pump",
  "gift",
  "graduation-cap",
  "hamburger",
  "hammer",
  "handshake",
  "headphones",
  "heart",
  "home",
  "hotel",
  "house-user",
  "key",
  "landmark",
  "laptop",
  "leaf",
  "lightbulb",
  "map",
  "medkit",
  "mobile-alt",
  "money-bill",
  "money-bill-wave",
  "motorcycle",
  "music",
  "paint-brush",
  "parking",
  "paw",
  "pen",
  "phone",
  "pills",
  "pizza-slice",
  "plane",
  "plug",
  "prescription-bottle",
  "receipt",
  "recycle",
  "running",
  "seedling",
  "shopping-bag",
  "shopping-basket",
  "shopping-cart",
  "shower",
  "snowflake",
  "socks",
  "spa",
  "star",
  "subway",
  "suitcase",
  "suitcase-rolling",
  "swimmer",
  "syringe",
  "tablet",
  "theater-masks",
  "thermometer-half",
  "tint",
  "toilet",
  "tools",
  "train",
  "trash",
  "tshirt",
  "umbrella-beach",
  "utensils",
  "volleyball-ball",
  "wallet",
  "wifi",
  "wine-bottle",
  "wrench",
] as const;

export type CategoryIconName = (typeof CATEGORY_ICON_CHOICES)[number];

/** Default icon when adding a category */
export const DEFAULT_CATEGORY_ICON = "shopping-cart";

const iconSet = new Set<string>(
  CATEGORY_ICON_CHOICES as unknown as readonly string[],
);

export function resolveCategoryIcon(
  icon: string | null | undefined,
  fallbackIcon: string = DEFAULT_CATEGORY_ICON,
): string {
  const n = typeof icon === "string" ? icon.trim() : "";
  if (n !== "" && iconSet.has(n)) return n;
  return fallbackIcon;
}
